#!/bin/bash
#*****************************************************************************
#* Function name  : TestAll
#* Description    : Run 3 tests on a given tests list- testCompile, testInOut,
#*					and testMem. print number of test passed.
#* Parameters	  : $1 - file contains the tests list
#* Return Value   : 1 if the lofFiles dir exists and no tests need to run. 
#*          0 if the tests were running and output number of tests passed.
#*****************************************************************************
if [[ -d logFiles ]]; then
	echo "error" # logFiles dir exists- no need to run tests
	exit 1
fi
mkdir logFiles
# initial counters for line number, num of tests and num of tests succeeded
lineNum=1
successNum=0
checkNum=0

while IFS=@ read -a line; do # each parameter in the line is seperated by '@'
	if [[ -z ${line} ]]; then # line is empty- skip the line
		continue
	fi
	checkName=${line[0]}
	progName=${line[1]}
	input=${line[2]}
	output=${line[3]}
	echo "${lineNum}: ${checkName}"
	# first test- compilation
	testCompile ./logFiles/${lineNum}.compile.log ${progName}
	if (( $?==0 )); then
		((successNum++))
	fi
	((checkNum++))
	# second test- input output
	testInOut ./logFiles/${lineNum}.inout.log ${progName} ${input} ${output}
	if (( $?==0 )); then
    	((successNum++))
	fi
	((checkNum++))
	# third test- memory
	testMem ./logFiles/${lineNum}.memory.log ${progName} ${input}
	if (( $?==0 )); then
		((successNum++))
	fi
	((checkNum++))

	((lineNum++)) # increment to get the next line
done < $1
echo "${successNum} tests passed out of ${checkNum}"
exit 0

