#!/bin/bash

#****************************************************
#Function name: testCompile
#Description: compiles the file and checks whether there have been any errors or warnings during the compilation
#Paramaters: 1 - log file which will contain the compilation results
#2 - Input file which we will compile
#Return value: 0 for a successful compilation, 1 for a compilation which failed
#****************************************************

gcc -g -Wall -o "$2" "$2.c" 2> "$1"

#We search for errors or warnings in the compliation. If we find any, we shall return a massege stating failure
if grep -e "error" -e "warning" $1 > /dev/null
then
	echo "Compile failed"
	exit 1
else
	echo "Compile succeeded"
	exit 0
fi