#!/bin/bash
#*****************************************************************************
#* Function name  : TestMem
#* Description    : Run program with input file using valgrind tool to test
#*					memory usage of program including error and leaks, and save its output in log file.
#* Parameters	  : $1 - log file to save valgrind output
#*					$2 - program to run
#*					$3 - input file for the program
#* Return Value   : 0 if the memery check in valgrind passed. 1 if the memory check failed- there is an error or leak
#*****************************************************************************
log_file=$1
prog_file=$2
input_file=$3
# run program in valgrind with input, save program output in null and log output in log file
valgrind --tool=memcheck "./${prog_file}" < "${input_file}" 2> "${log_file}" > /dev/null

# check errors or leaks with two conditions- "0 errors" in ERROR SUMMARY and "no leaks are possible "in LEAK SUMMARY
if ( ( grep -e "ERROR SUMMARY: 0 errors" ${log_file} > /dev/null ) && ( grep -e "no leaks are possible" ${log_file} > /dev/null ) ); then # if found 0 errors in error summary and found no leaks are possible - no errors and no leaks, test passed
	echo "Memory test passed"
 	exit 0
else # found memory error in error summary, or found leaks in leak summary
	echo "Memory test failed"
	exit 1
fi